// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwQ5sI0LegtSKkHXKykRxCINbw_iOevI',
    appId: '1:880608402475:web:9fd929ccaa8d3c8a319e6e',
    messagingSenderId: '880608402475',
    projectId: 'news-d9127',
    authDomain: 'news-d9127.firebaseapp.com',
    storageBucket: 'news-d9127.appspot.com',
    measurementId: 'G-EKVYB12WDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfZUskCJekavy5IjNdzysR2mU9GiCIjU',
    appId: '1:880608402475:android:adaac009f9f26712319e6e',
    messagingSenderId: '880608402475',
    projectId: 'news-d9127',
    storageBucket: 'news-d9127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3kCorqawwmg-kJ3jqU-puYFisKxtYrLs',
    appId: '1:880608402475:ios:b08712b807035f2c319e6e',
    messagingSenderId: '880608402475',
    projectId: 'news-d9127',
    storageBucket: 'news-d9127.appspot.com',
    iosBundleId: 'com.example.nnews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3kCorqawwmg-kJ3jqU-puYFisKxtYrLs',
    appId: '1:880608402475:ios:b08712b807035f2c319e6e',
    messagingSenderId: '880608402475',
    projectId: 'news-d9127',
    storageBucket: 'news-d9127.appspot.com',
    iosBundleId: 'com.example.nnews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGwQ5sI0LegtSKkHXKykRxCINbw_iOevI',
    appId: '1:880608402475:web:8a7b7cf18cc9052f319e6e',
    messagingSenderId: '880608402475',
    projectId: 'news-d9127',
    authDomain: 'news-d9127.firebaseapp.com',
    storageBucket: 'news-d9127.appspot.com',
    measurementId: 'G-2XX7JK7HKT',
  );
}
